### ISSUE TITLE
Display AnalysisImage 

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [Apparence-io/CamerAwesome#208]
Hi ,I try to display AnalysisImage when listen on onImageForAnalysis . 
But i can not found any document about this.

**Comment by istornz** [comment]
Hello @CaoGiaHieu-dev, you can check the official [documentation](https://docs.page/Apparence-io/camera_awesome/ai_with_mlkit/detecting_faces).

You can also check our [examples](https://github.com/Apparence-io/CamerAwesome/tree/master/example/lib) 👍

**Comment by CaoGiaHieu-dev** [comment]
> Hello @CaoGiaHieu-dev, you can check the official [documentation](https://docs.page/Apparence-io/camera_awesome/ai_with_mlkit/detecting_faces).
> 
> You can also check our [examples](https://github.com/Apparence-io/CamerAwesome/tree/master/example/lib) 👍

Thanks . But i still cant found any example or doc to display AnalysisImage from onImageForAnalysis

**Comment by istornz** [comment]
In examples, you have a ```InputImage inputImage``` object like [here](https://github.com/Apparence-io/CamerAwesome/blob/877702d1c105d2dae8ef1700825f2e6cc09c588c/example/lib/ai_analysis_barcode.dart#L107).

You can found a ```Uint8List``` property inside it: ```inputImage.bytes```, so you can display it like this (for example): ```Image.memory(Uint8List bytes);```

**Comment by CaoGiaHieu-dev** [comment]
I try to follow your example and display inputImage.bytes but it show this error
════════ Exception caught by image resource service ════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack
#0      _futurize (dart:ui/painting.dart:5522:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5390:12)
#2      instantiateImageCodec (dart:ui/painting.dart:2053:60)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════

**Comment by g-apparence** [comment]
If you want to display it you have to use a format jpeg. 
Or you can convert it before showing it.

**Comment by CaoGiaHieu-dev** [comment]
> If you want to display it you have to use a format jpeg. Or you can convert it before showing it.
Thanks @g-apparence . that all i want . 
Can you show me an example code . Thank you

**Comment by apalala-dev** [comment]
I will provide you an example :)

**Comment by CaoGiaHieu-dev** [comment]
> I will provide you an example :) Are you on iOS or Android?

im want to show it on android .

**Comment by apalala-dev** [comment]
It is not as trivial as I though :/
Since the format is not the typical one displayed in a Flutter Image, there is some conversion to do and the best way to do that is to do it on the native side, which involves method channels etc.
Can you give use your use case for this?
Doing the conversion for each frame in _nv21_ for analysis **and** in _jpeg_ for displaying should be quite demanding as well.

**Comment by CaoGiaHieu-dev** [comment]
im stuck in this issue even i try to call back image from native side like CameraImage of Camera package

**Comment by apalala-dev** [comment]
I've tried a similar approach but it requires more work and maybe some changes from CamerAwesome for this to work.

Can you explain why you are trying to display the analysis image?

**Comment by CaoGiaHieu-dev** [comment]
> I've tried a similar approach but it requires more work and maybe some changes from CamerAwesome for this to work.
> 
> Can you explain why you are trying to display the analysis image?

It more like an ekyc bussiness and i need image of action to verify user.

**Comment by CaoGiaHieu-dev** [comment]
@apalala-dev 
Hi . any update on this ?

**Comment by apalala-dev** [comment]
Hi, not yet sorry.
You'll be able to track progress on this in #218.

The idea would be to rework the `AnalysisConfig` and `AnalysisImage`. The later one could include both an analysis image (e.g.: NV21 for android) AND a jpeg one if necessary to be able to display it.
Some tests need to be done first as it will duplicate the image and treatment for every frame (it might be done every X frames or something like that, not sure yet).

An other option would be to provide a method to convert analysis images (nv21...) to more traditional JPEG. This way, you would have to do it on demand. It might be simpler to implement but less performant.

**Comment by CaoGiaHieu-dev** [comment]
> convert analysis images (nv21...) to more traditional JPEG

i found this https://github.com/google-ar/sceneform-android-sdk/issues/965 and the AwesomeCamera was retrun the nv21 bytes .

**Comment by apalala-dev** [comment]
We almost have the technical part (like what you sent) but we need to figure out a good API to use it.
If you really need it fast, you can use the sent code and convert the nv21 image with method channels.

**Comment by CaoGiaHieu-dev** [comment]
> We almost have the technical part (like what you sent) but we need to figure out a good API to use it. If you really need it fast, you can use the sent code and convert the nv21 image with method channels.

@apalala-dev  I was force your package version 1.3.1 and add this code to get display image 
```
private fun getDisplayImage(imageProxy: ImageProxy): ByteArray {
        val image = imageProxy.getImage();

        val planes = image!!.getPlanes();
        val yBuffer = planes[0].getBuffer();
        val uBuffer = planes[1].getBuffer();
        val vBuffer = planes[2].getBuffer();

        val ySize = yBuffer.remaining();
        val uSize = uBuffer.remaining();
        val vSize = vBuffer.remaining();

        val nv21 = ImageUtil.yuv_420_888toNv21(imageProxy)
        //U and V are swapped
        yBuffer.get(nv21, 0, ySize);
        vBuffer.get(nv21, ySize, vSize);
        uBuffer.get(nv21, ySize + vSize, uSize);

        val yuvImage = YuvImage(nv21, ImageFormat.NV21, image.width, image.height, null);
        val out = ByteArrayOutputStream();
        yuvImage.compressToJpeg(Rect(0, 0, yuvImage.getWidth(), yuvImage.getHeight()), 100, out);
        return rotateImage(out.toByteArray(), imageProxy);
    }
```
and for return 
```
 when (format) {
                OutputImageFormat.JPEG -> {
                    val jpegImage = ImageUtil.yuvImageToJpegByteArray(
                        imageProxy, Rect(0, 0, imageProxy.width, imageProxy.height), 100
                    )
                    val imageMap = imageProxyBaseAdapter(imageProxy)

                    imageMap["jpegImage"] = jpegImage
                    imageMap["cropRect"] = cropRect(imageProxy)
                    imageMap["displayImage"] = getDisplayImage(imageProxy)
                    executor.execute { previewStreamSink?.success(imageMap) }
                }
                OutputImageFormat.YUV_420_888 -> {
                    val planes = imagePlanesAdapter(imageProxy)
                    val imageMap = imageProxyBaseAdapter(imageProxy)

                    imageMap["planes"] = planes
                    imageMap["cropRect"] = cropRect(imageProxy)
                    imageMap["displayImage"] = getDisplayImage(imageProxy)
                    executor.execute { previewStreamSink?.success(imageMap) }
                }
                OutputImageFormat.NV21 -> {
                    val nv21Image = ImageUtil.yuv_420_888toNv21(imageProxy)
                    val planes = imagePlanesAdapter(imageProxy)
                    val imageMap = imageProxyBaseAdapter(imageProxy)
                    imageMap["nv21Image"] = nv21Image
                    imageMap["planes"] = planes
                    imageMap["cropRect"] = cropRect(imageProxy)
                    imageMap["displayImage"] = getDisplayImage(imageProxy)
                    executor.execute { previewStreamSink?.success(imageMap) }
                }
            }
```
could you take a look on this and if it ok could you do the same with ios too? (sorry im not good at swift / objc)
