### ISSUE TITLE
Platform Exception CANNOT OPEN CAMERA. Running it in ios simulator.

### ISSUE THREAD

**Issue by chitgoks** [Apparence-io/CamerAwesome#239]
I just copied the sample code of the camera awesome builder. when the widget loads, it gets this error. in a real iphone device, it runs ok.

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(CANNOT_OPEN_CAMERA, can't attach device to input, Cannot Record, null)
#0      CameraInterface.setupCamera (package:camerawesome/pigeon.dart:235:7)
<asynchronous suspension>
#1      PreparingCameraState._init (package:camerawesome/src/orchestrator/states/preparing_camera_state.dart:118:5)
<asynchronous suspension>
#2      PreparingCameraState._startPhotoMode (package:camerawesome/src/orchestrator/states/preparing_camera_state.dart:102:5)
<asynchronous suspension>
#3      PreparingCameraState.start (package:camerawesome/src/orchestrator/states/preparing_camera_state.dart:34:9)
<asynchronous suspension>
```

**Comment by chitgoks** [comment]
ok nevermind. just read 2 posts now that ios simulator cannot simulate using camera. androif can though.
