### ISSUE TITLE
onImageForAnalysis prevents video recording on iOS

### ISSUE THREAD

**Issue by Parfyonator** [Apparence-io/CamerAwesome#421]
## Steps to Reproduce

Add `onImageForAnalysis` callback to example app. It can be as simple as

```
onImageForAnalysis: (image) async {
  print('######################');
  print(image.toInputImage());
  print('######################');
}
```

## Expected results

Video is recorded and available for playback after pressing the "Stop" button.

## Actual results

I get the following error in logs

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VIDEO_ERROR, video is not recording, , null)
#0      CameraInterface.stopRecordingVideo (package:camerawesome/pigeon.dart:983:7)
<asynchronous suspension>
#1      VideoRecordingCameraState.stopRecording (package:camerawesome/src/orchestrator/states/video_camera_recording_state.dart:87:20)
<asynchronous suspension>
```

I cannot stop video recording due to this error.

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone 11*  | *17.1.1*  |

## Your flutter version

```
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (6 weeks ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0
```

</details>

**Comment by g-apparence** [comment]
Could you post your code? 
Were you actually recording a video while performing analysis?

**Comment by Parfyonator** [comment]
Hi @g-apparence. I've already posted it. It is literally only that 5 lines of additional code added to `CameraAwesomeBuilder.awesome` in main file of example. That's it. Nothing more. I don't see any sense in duplicating all of the code for these 5 lines.
You can even leave this function empty to reproduce the issue: `onImageForAnalysis: (image) async {}`.

**Comment by Parfyonator** [comment]
@g-apparence additional note about video recording: I'm using the built in functionality of `CameraAwesomeBuilder.awesome` widget. Here is video recording of the screen. When I press stop button, I get the error I've mentioned in the issue description.

https://github.com/Apparence-io/CamerAwesome/assets/27166027/4d8d4cdd-da0b-45e3-84e8-05fe4c0c0b8b

**Comment by g-apparence** [comment]
Will make a try and tell you. 
Sorry for delay

**Comment by Parfyonator** [comment]
Hi @g-apparence. I decided to dig a bit deeper and added some prints to [`video_camera_state.dart`](https://github.com/Apparence-io/CamerAwesome/blob/5a24be3e8525bb7236364889ea45f6da554a604e/lib/src/orchestrator/states/video_camera_state.dart#L36) and it throws an error when `onImageForAnalysis` is present. Since `await CamerawesomePlugin.recordVideo(captureRequest);` is wrapped in try block it is not visible in logs.

```
flutter: PlatformException(VIDEO_ERROR, can't record video when image stream is enabled, , null)
flutter: #0      CameraInterface.recordVideo (package:camerawesome/pigeon.dart:899:7)
<asynchronous suspension>
#1      VideoCameraState.startRecording (package:camerawesome/src/orchestrator/states/video_camera_state.dart:48:7)
<asynchronous suspension>
```

Maybe that will help.

**Comment by Parfyonator** [comment]
Hi @g-apparence. Don't want to be pushy, just want to know if it is something that can be fixed relatively quickly or I should switch to camera plugin on iOS devices for now. Thanks.

**Comment by g-apparence** [comment]
Hi sorry, I have a lot of work on the ApparenceKit Supabase support. 

I'm not sure that it is a problem with camerawesome or that this should not be possible on all devices. 
I have to take time and try this on all the devices I have for CamerAwesome. 

Also I'm always open for contribution if you wanna help me on this.

**Comment by Parfyonator** [comment]
I'm not good at native development especially Objective-C. So I'm not sure how to fix it. Also I'm not sure if I'll have time to dig into native iOS part in the nearest since I have multiple projects.

**Comment by SacadM** [comment]
Are there any updates on this?

**Comment by haf** [comment]
Seconded; even `.custom` as a builder causes this issue

<img width="331" alt="Image" src="https://github.com/user-attachments/assets/dec7365f-8f7f-43c6-8a5c-241e8c8d9480" />
