### ISSUE TITLE
Access denied finding property "vendor.camera.aux.packagelist" when I updated to camerawesome 2.0.0+1 and video camera doesn't work

### ISSUE THREAD

**Issue by MichaelSowah** [Apparence-io/CamerAwesome#423]
## Steps to Reproduce

Install camerawesome 2.0.0+1, using default UI or custom UI, run app and start the video camera, it freezes and unable to record video. This doesn't happen when I use camerawesome 1.4.0.

## Expected results

Video camera should not freeze and video recording should record

## Actual results

The video camera freezes and am unable to record. Then I see this in the logs

W/libc    (18838): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal(18838): ignore the torch status update of camera: 5
W/libc    (18838): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal(18838): [soar.cts] ignore the status update of camera: 5
W/libc    (18838): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal(18838): [soar.cts] ignore the status update of camera: 4
W/libc    (18838): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal(18838): ignore the torch status update of camera: 3
W/libc    (18838): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal(18838): [soar.cts] ignore the status update of camera: 3
E/CameraManagerGlobal(18838): Camera 5 is not available. Ignore physical camera status change
W/libc    (18838): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal(18838): [soar.cts] ignore the status update of camera: 2
W/libc    (18838): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    (18838): Access denied finding property "vendor.camera.aux.packagelist"
E/CameraManagerGlobal(18838): Camera 5 is not available. Ignore physical camera status change
W/libc    (18838): Access denied finding property "vendor.camera.aux.packagelist"

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Nokia* | *Nokia X20*  | *Android 13*  |

## Your flutter version

Run this in your command line 
```flutter --version```

*Flutter 3.16.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0366e0a3f (7 days ago) • 2023-12-05 19:46:39 -0800
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
*

</details>

**Comment by g-apparence** [comment]
Hi, 
Sorry fo that. There should be a reason of this.
The message is clearly a permission error. 

Did you add this in your manifest 
```xml
<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />

<application ...>
    ...
</application>
```

If you refused the permission by error, go to your settings and change it. (Or reinstall your app). 

Let me know

**Comment by MichaelSowah** [comment]
After adding the above and allowing permissions, still did not work and these are the logs I get 

 ( 8179): Access denied finding property "persist.vendor.camera.privapp.list"
W/libc    ( 8179): Access denied finding property "persist.vendor.camera.privapp.list"
W/libc    ( 8179): Access denied finding property "persist.vendor.camera.privapp.list"
D/CompatibilityChangeReporter( 8179): Compat change id reported: 78294732; UID 10464; state: ENABLED
D/com.apparence.camerawesome.cameraX.CameraPermissions( 8179): _onRequestPermissionsResult: received permissions but the EventSink is closed
W/libc    ( 8179): Access denied finding property "persist.vendor.camera.privapp.list"
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
E/CameraManagerGlobal( 8179): Camera 5 is not available. Ignore physical camera status change
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
D/PipelineWatcher( 8179): DEBUG: elapsed 0 / 4
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): ignore the torch status update of camera: 3
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): ignore the torch status update of camera: 5
E/CameraManagerGlobal( 8179): Camera 5 is not available. Ignore physical camera status change
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
E/CameraCaptureSession( 8179): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession( 8179): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession( 8179): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2470)
E/CameraCaptureSession( 8179): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1341)
E/CameraCaptureSession( 8179): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:580)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.SynchronizedCaptureSessionBaseImpl.close(SynchronizedCaptureSessionBaseImpl.java:476)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.CaptureSession.release(CaptureSession.java:526)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl.releaseSession(Camera2CameraImpl.java:555)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl.resetCaptureSession(Camera2CameraImpl.java:1329)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl.closeCamera(Camera2CameraImpl.java:468)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl$StateCallback.reopenCameraAfterError(Camera2CameraImpl.java:1827)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl$StateCallback.handleErrorOnOpen(Camera2CameraImpl.java:1779)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl$StateCallback.onError(Camera2CameraImpl.java:1754)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.CameraDeviceStateCallbacks$ComboDeviceStateCallback.onError(CameraDeviceStateCallbacks.java:121)
E/CameraCaptureSession( 8179): 	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1850)
E/CameraCaptureSession( 8179): 	at android.hardware.camera2.impl.CameraDeviceImpl.$r8$lambda$KBQCqQRdhVVn7uHI9Xdha6OqnsU(Unknown Source:0)
E/CameraCaptureSession( 8179): 	at android.hardware.camera2.impl.CameraDeviceImpl$$ExternalSyntheticLambda0.accept(Unknown Source:8)
E/CameraCaptureSession( 8179): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:281)
E/CameraCaptureSession( 8179): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
E/CameraCaptureSession( 8179): 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
E/CameraCaptureSession( 8179): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$1.run(SequentialExecutor.java:111)
E/CameraCaptureSession( 8179): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:231)
E/CameraCaptureSession( 8179): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:173)
E/CameraCaptureSession( 8179): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/CameraCaptureSession( 8179): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/CameraCaptureSession( 8179): 	at java.lang.Thread.run(Thread.java:1012)
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
E/CameraManagerGlobal( 8179): Camera 5 is not available. Ignore physical camera status change
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 2
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 3
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 4
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 5
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): ignore the torch status update of camera: 5
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 5
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 4
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): ignore the torch status update of camera: 3
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 3
E/CameraManagerGlobal( 8179): Camera 5 is not available. Ignore physical camera status change
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 2
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
E/CameraManagerGlobal( 8179): Camera 5 is not available. Ignore physical camera status change
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    ( 8179): Access denied finding property "persist.vendor.camera.privapp.list"
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
E/CameraManagerGlobal( 8179): Camera 5 is not available. Ignore physical camera status change
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): ignore the torch status update of camera: 3
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): ignore the torch status update of camera: 5
E/CameraManagerGlobal( 8179): Camera 5 is not available. Ignore physical camera status change
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
E/CameraCaptureSession( 8179): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession( 8179): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession( 8179): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2470)
E/CameraCaptureSession( 8179): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1341)
E/CameraCaptureSession( 8179): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:580)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.SynchronizedCaptureSessionBaseImpl.close(SynchronizedCaptureSessionBaseImpl.java:476)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.CaptureSession.release(CaptureSession.java:526)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl.releaseSession(Camera2CameraImpl.java:555)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl.resetCaptureSession(Camera2CameraImpl.java:1329)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl.closeCamera(Camera2CameraImpl.java:468)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl$StateCallback.reopenCameraAfterError(Camera2CameraImpl.java:1827)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl$StateCallback.handleErrorOnOpen(Camera2CameraImpl.java:1779)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl$StateCallback.onError(Camera2CameraImpl.java:1754)
E/CameraCaptureSession( 8179): 	at androidx.camera.camera2.internal.CameraDeviceStateCallbacks$ComboDeviceStateCallback.onError(CameraDeviceStateCallbacks.java:121)
E/CameraCaptureSession( 8179): 	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1850)
E/CameraCaptureSession( 8179): 	at android.hardware.camera2.impl.CameraDeviceImpl.$r8$lambda$KBQCqQRdhVVn7uHI9Xdha6OqnsU(Unknown Source:0)
E/CameraCaptureSession( 8179): 	at android.hardware.camera2.impl.CameraDeviceImpl$$ExternalSyntheticLambda0.accept(Unknown Source:8)
E/CameraCaptureSession( 8179): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:281)
E/CameraCaptureSession( 8179): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
E/CameraCaptureSession( 8179): 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
E/CameraCaptureSession( 8179): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$1.run(SequentialExecutor.java:111)
E/CameraCaptureSession( 8179): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:231)
E/CameraCaptureSession( 8179): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:173)
E/CameraCaptureSession( 8179): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/CameraCaptureSession( 8179): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/CameraCaptureSession( 8179): 	at java.lang.Thread.run(Thread.java:1012)
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
E/CameraManagerGlobal( 8179): Camera 5 is not available. Ignore physical camera status change
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 2
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 3
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 4
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 5
E/SequentialExecutor( 8179): Exception while executing runnable androidx.camera.core.impl.utils.executor.SequentialExecutor$1@5cc9781
E/SequentialExecutor( 8179): java.lang.IllegalArgumentException: getCameraCharacteristics:774: Unable to retrieve camera characteristics for unknown device 0: No such file or directory (-2)
E/SequentialExecutor( 8179): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1385)
E/SequentialExecutor( 8179): 	at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:606)
E/SequentialExecutor( 8179): 	at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:677)
E/SequentialExecutor( 8179): 	at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:973)
E/SequentialExecutor( 8179): 	at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:994)
E/SequentialExecutor( 8179): 	at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:872)
E/SequentialExecutor( 8179): 	at androidx.camera.camera2.internal.compat.CameraManagerCompatApi29Impl.openCamera(CameraManagerCompatApi29Impl.java:44)
E/SequentialExecutor( 8179): 	at androidx.camera.camera2.internal.compat.CameraManagerCompat.openCamera(CameraManagerCompat.java:232)
E/SequentialExecutor( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl.openCameraDevice(Camera2CameraImpl.java:1138)
E/SequentialExecutor( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl.tryForceOpenCameraDevice(Camera2CameraImpl.java:1077)
E/SequentialExecutor( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl$StateCallback$ScheduledReopen.lambda$run$0$androidx-camera-camera2-internal-Camera2CameraImpl$StateCallback$ScheduledReopen(Camera2CameraImpl.java:1923)
E/SequentialExecutor( 8179): 	at androidx.camera.camera2.internal.Camera2CameraImpl$StateCallback$ScheduledReopen$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/SequentialExecutor( 8179): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$1.run(SequentialExecutor.java:111)
E/SequentialExecutor( 8179): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:231)
E/SequentialExecutor( 8179): 	at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:173)
E/SequentialExecutor( 8179): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/SequentialExecutor( 8179): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/SequentialExecutor( 8179): 	at java.lang.Thread.run(Thread.java:1012)
E/SequentialExecutor( 8179): Caused by: android.os.ServiceSpecificException: getCameraCharacteristics:774: Unable to retrieve camera characteristics for unknown device 0: No such file or directory (-2) (code 3)
E/SequentialExecutor( 8179): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3025)
E/SequentialExecutor( 8179): 	at android.os.Parcel.createException(Parcel.java:2995)
E/SequentialExecutor( 8179): 	at android.os.Parcel.readException(Parcel.java:2978)
E/SequentialExecutor( 8179): 	at android.os.Parcel.readException(Parcel.java:2920)
E/SequentialExecutor( 8179): 	at android.hardware.ICameraService$Stub$Proxy.getCameraCharacteristics(ICameraService.java:754)
E/SequentialExecutor( 8179): 	at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:585)
E/SequentialExecutor( 8179): 	... 16 more
I/hw-BpHwBinder( 8179): onLastStrongRef automatically unlinking death recipients
I/BpBinder( 8179): onLastStrongRef automatically unlinking death recipients: android.media.IResourceManagerService
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): ignore the torch status update of camera: 5
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 5
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 4
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): ignore the torch status update of camera: 3
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 3
E/CameraManagerGlobal( 8179): Camera 5 is not available. Ignore physical camera status change
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal( 8179): [soar.cts] ignore the status update of camera: 2
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
E/CameraManagerGlobal( 8179): Camera 5 is not available. Ignore physical camera status change
W/libc    ( 8179): Access denied finding property "vendor.camera.aux.packagelist"
D/BufferPoolAccessor2.0( 8179): bufferpool2 0xb400007676cabe98 : 0(0 size) total buffers - 0(0 size) used buffers - 25/35 (recycle/alloc) - 5/30 (fetch/transfer)
D/BufferPoolAccessor2.0( 8179): Destruction - bufferpool2 0xb400007676cabe98 cached: 0/0M, 0/0% in use; allocs: 35, 71% recycled; transfers: 30, 83% unfetched
D/BufferPoolAccessor2.0( 8179): evictor expired: 1, evicted: 0

**Comment by MichaelSowah** [comment]
any updates...

**Comment by kauemurakami** [comment]
Same problem

**Comment by ankiimation** [comment]
any updates...
