### ISSUE TITLE
AwesomeZoomSelector not working on iOS

### ISSUE THREAD

**Issue by giordy16** [Apparence-io/CamerAwesome#458]
## Steps to Reproduce

*I'm trying to use a AwesomeZoomSelector on my custom UI, bust a cast exception is thrown There is a similar issue:*
 #https://github.com/Apparence-io/CamerAwesome/issues/435

## Expected results

*The zoom values are returned*

## Actual results

*A cast exception is thrown*
```
flutter: type 'int' is not a subtype of type 'double?' in type cast
flutter: Stacktrace: #0      CameraInterface.getMinZoom (package:camerawesome/pigeon.dart:1289:28)
flutter: <asynchronous suspension>
flutter: #1      _AwesomeZoomSelectorState.initAsync (package:camerawesome/src/widgets/zoom/awesome_zoom_selector.dart:27:15)
flutter: <asynchronous suspension>
flutter:
```

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone 14*  | *17.3.1*  |

## Your flutter version

*Flutter 3.16.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 67457e669f (2 months ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5
*

</details>

**Comment by Madnex** [comment]
Actually after digging into the code I found that the `AwesomeZoomSelector` is only used for Android. For iOS there is the `AwesomeSensorTypeSelector`. See [here](https://github.com/Apparence-io/CamerAwesome/blob/a6715d98a8511a4c7fe736fbdd61ac97f53c231c/lib/src/widgets/filters/awesome_filter_widget.dart#L87) how they make the selection.

**Comment by giordy16** [comment]
@Madnex Thank you, but I already saw that. I would like to use `AwesomeZoomSelector ` because it displays the current zoom level while zooming, a thing that  `AwesomeSensorTypeSelector ` doesn't have.
